#!/bin/sh

if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
elif command -v python >/dev/null 2>&1; then
    PYTHON=python
else
    echo "Error: python not found in PATH"
    exit 1
fi

$PYTHON scripts/code_format.py --check --staged